from models.schemas import BankingModule, TestCase, TestType

CREDIT_CARDS_SUITE: list[TestCase] = [
    TestCase(
        name="List credit cards — default pagination",
        description="GET /api/v1/credit-cards returns 200 with card list and total.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/credit-cards",
        expected_status=200,
        expected_fields=["cards", "total", "limit"],
    ),
    TestCase(
        name="List credit cards — status=BLOCKED filter",
        description="Filtered list must only return BLOCKED cards.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/credit-cards?status=BLOCKED",
        expected_status=200,
        expected_fields=["cards", "total"],
    ),
    TestCase(
        name="Get card — valid ID",
        description="Single card endpoint returns full card data without card_number_hash.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/credit-cards/{card_id}",
        expected_status=200,
        expected_fields=["card_number_masked", "credit_limit", "available_credit", "status"],
    ),
    TestCase(
        name="Get card — card_number_hash must NOT appear in response",
        description="Security: raw card_number_hash must never be exposed via the API.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.SECURITY,
        method="GET", endpoint="/api/v1/credit-cards/{card_id}",
        expected_status=200,
    ),
    TestCase(
        name="Get card — non-existent ID returns 404",
        description="Valid ObjectId that has no card must return 404.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/credit-cards/{nonexistent_id}",
        expected_status=404,
    ),
    TestCase(
        name="Block card — active card with valid reason",
        description="POST block on an ACTIVE card must return 200 and status=BLOCKED.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/credit-cards/{active_card_id}/block",
        payload={"reason": "AQE automated block test — valid reason"},
        expected_status=200,
        expected_fields=["status", "masked", "blocked_at"],
    ),
    TestCase(
        name="Block card — already BLOCKED returns 400",
        description="Attempting to block an already-BLOCKED card must return 400.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/credit-cards/{blocked_card_id}/block",
        payload={"reason": "duplicate block attempt"},
        expected_status=400,
    ),
    TestCase(
        name="Block card — reason too short returns 422",
        description="Reason with < 3 characters must fail Pydantic validation (422).",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/credit-cards/{card_id}/block",
        payload={"reason": "ab"},
        expected_status=422,
    ),
    TestCase(
        name="Block card — non-existent card returns 404",
        description="Block on a card ObjectId that doesn't exist must return 404.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/credit-cards/{nonexistent_id}/block",
        payload={"reason": "testing nonexistent card"},
        expected_status=404,
    ),
    TestCase(
        name="List cards — status filter returns consistent results",
        description="Cards returned when filtering by status=ACTIVE must all have status=ACTIVE.",
        module=BankingModule.CREDIT_CARDS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/credit-cards?status=ACTIVE",
        expected_status=200,
        expected_fields=["cards"],
    ),
]
