from models.schemas import BankingModule, TestCase, TestType

CUSTOMERS_SUITE: list[TestCase] = [
    TestCase(
        name="List customers — default pagination",
        description="GET /api/v1/customers returns 200 with a customer list and total count.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/customers",
        expected_status=200,
        expected_fields=["customers", "total", "limit", "skip"],
    ),
    TestCase(
        name="List customers — KYC_STATUS=VERIFIED filter",
        description="Filter by kyc_status=VERIFIED; all returned customers must be VERIFIED.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/customers?kyc_status=VERIFIED",
        expected_status=200,
        expected_fields=["customers", "total"],
    ),
    TestCase(
        name="List customers — KYC_STATUS=REJECTED filter",
        description="Filter by kyc_status=REJECTED; validates edge-case customers are reachable.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/customers?kyc_status=REJECTED",
        expected_status=200,
        expected_fields=["customers", "total"],
    ),
    TestCase(
        name="List customers — limit=1 boundary",
        description="Pagination boundary: limit=1 must return exactly one record.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/customers?limit=1",
        expected_status=200,
        expected_fields=["customers"],
    ),
    TestCase(
        name="Get customer portfolio — valid ID",
        description="Returns full portfolio (accounts, cards, deposits) for a seeded customer.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/customers/{customer_id}/portfolio",
        expected_status=200,
        expected_fields=["customer", "accounts", "credit_cards", "fixed_deposits", "summary"],
    ),
    TestCase(
        name="Get customer portfolio — edge case BLOCKED card",
        description="Edge-case customer with a BLOCKED credit card must still return 200 portfolio.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/customers/{edge_customer_blocked}/portfolio",
        expected_status=200,
        expected_fields=["credit_cards"],
    ),
    TestCase(
        name="Get customer portfolio — REJECTED KYC + FROZEN account",
        description="Edge-case customer (KYC=REJECTED, account=FROZEN) must still return portfolio.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/customers/{edge_customer_frozen}/portfolio",
        expected_status=200,
    ),
    TestCase(
        name="Get customer portfolio — invalid ObjectId format",
        description="Non-ObjectId customer_id must return 422 Unprocessable Entity.",
        module=BankingModule.CUSTOMERS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/customers/not-a-valid-id/portfolio",
        expected_status=422,
    ),
]
