from models.schemas import BankingModule, TestCase, TestType

DEPOSITS_SUITE: list[TestCase] = [
    TestCase(
        name="List fixed deposits — default pagination",
        description="GET /api/v1/fixed-deposits returns list with depositor info.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/fixed-deposits",
        expected_status=200,
        expected_fields=["deposits", "total"],
    ),
    TestCase(
        name="List fixed deposits — status=ACTIVE filter",
        description="All returned deposits must have status=ACTIVE.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/fixed-deposits?status=ACTIVE",
        expected_status=200,
        expected_fields=["deposits"],
    ),
    TestCase(
        name="Get fixed deposit — valid ID",
        description="Single deposit endpoint returns full deposit data.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.FUNCTIONAL,
        method="GET", endpoint="/api/v1/fixed-deposits/{deposit_id}",
        expected_status=200,
        expected_fields=["principal_amount", "interest_rate_apy", "tenure_months", "status"],
    ),
    TestCase(
        name="Get fixed deposit — non-existent ID returns 404",
        description="Valid ObjectId with no matching deposit must return 404.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.EDGE_CASE,
        method="GET", endpoint="/api/v1/fixed-deposits/{nonexistent_id}",
        expected_status=404,
    ),
    TestCase(
        name="Simulate maturity — standard case",
        description="$10,000 at 5.25% APY for 24 months; payout must be mathematically correct.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/fixed-deposits/simulate-maturity",
        payload={"principal_amount": 10000, "interest_rate_apy": 5.25, "tenure_months": 24},
        expected_status=200,
        expected_fields=["principal_amount", "interest_earned", "maturity_payout", "compounding"],
    ),
    TestCase(
        name="Simulate maturity — max APY boundary (20%)",
        description="Maximum allowed APY (20%) must succeed and return correct payout.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/fixed-deposits/simulate-maturity",
        payload={"principal_amount": 50000, "interest_rate_apy": 20, "tenure_months": 12},
        expected_status=200,
    ),
    TestCase(
        name="Simulate maturity — minimum tenure (1 month)",
        description="Minimum tenure (1 month) must return valid payout > principal.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/fixed-deposits/simulate-maturity",
        payload={"principal_amount": 5000, "interest_rate_apy": 6.0, "tenure_months": 1},
        expected_status=200,
    ),
    TestCase(
        name="Simulate maturity — APY above 20% returns 422",
        description="APY > 20 violates the Pydantic constraint and must return 422.",
        module=BankingModule.DEPOSITS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/fixed-deposits/simulate-maturity",
        payload={"principal_amount": 10000, "interest_rate_apy": 25, "tenure_months": 12},
        expected_status=422,
    ),
]
