from models.schemas import BankingModule, TestCase, TestType

TRANSACTIONS_SUITE: list[TestCase] = [
    TestCase(
        name="CREDIT to active CHECKING account",
        description="Credit $500 to an active checking account; balance must increase.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{account_id}", "entity_type": "ACCOUNT",
                 "type": "CREDIT", "amount": "500.00", "description": "AQE credit test"},
        expected_status=200,
        expected_fields=["transaction_ref", "status", "amount"],
    ),
    TestCase(
        name="DEBIT from active CHECKING account (sufficient funds)",
        description="Debit $100 from account with balance ≥ $100; must succeed.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{account_id}", "entity_type": "ACCOUNT",
                 "type": "DEBIT", "amount": "100.00"},
        expected_status=200,
        expected_fields=["status"],
    ),
    TestCase(
        name="DEBIT — insufficient funds returns 400",
        description="Debit exceeding the current balance must return 400 insufficient funds.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{account_id}", "entity_type": "ACCOUNT",
                 "type": "DEBIT", "amount": "9999999.00"},
        expected_status=400,
    ),
    TestCase(
        name="CREDIT to active SAVINGS account",
        description="Credit $200 to a savings account; validates SAVINGS entity type works.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{savings_account_id}", "entity_type": "ACCOUNT",
                 "type": "CREDIT", "amount": "200.00"},
        expected_status=200,
    ),
    TestCase(
        name="Execute on FROZEN account returns 400",
        description="Any transaction on a FROZEN account must be rejected with 400.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{frozen_account_id}", "entity_type": "ACCOUNT",
                 "type": "CREDIT", "amount": "50.00"},
        expected_status=400,
    ),
    TestCase(
        name="Duplicate transaction_ref returns 409",
        description="Submitting the same transaction_ref twice must return 409 Conflict.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{account_id}", "entity_type": "ACCOUNT",
                 "type": "CREDIT", "amount": "10.00",
                 "transaction_ref": "aqe-idempotency-test-fixed-ref"},
        expected_status=409,
    ),
    TestCase(
        name="DEBIT credit card — within limit",
        description="Credit card purchase within available_credit must succeed.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{card_id}", "entity_type": "CREDIT_CARD",
                 "type": "DEBIT", "amount": "50.00", "description": "card purchase"},
        expected_status=200,
    ),
    TestCase(
        name="DEBIT credit card — over limit returns 400",
        description="Purchase exceeding available_credit must return 400 over limit.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.EDGE_CASE,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{card_id}", "entity_type": "CREDIT_CARD",
                 "type": "DEBIT", "amount": "9999999.00"},
        expected_status=400,
    ),
    TestCase(
        name="CREDIT credit card (payment)",
        description="Card payment (CREDIT type) reduces current_balance.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{card_id}", "entity_type": "CREDIT_CARD",
                 "type": "CREDIT", "amount": "25.00", "description": "card payment"},
        expected_status=200,
    ),
    TestCase(
        name="INTEREST_ACCRUAL on fixed deposit",
        description="Interest accrual transaction on an ACTIVE fixed deposit must succeed.",
        module=BankingModule.TRANSACTIONS,
        test_type=TestType.FUNCTIONAL,
        method="POST", endpoint="/api/v1/transactions/execute",
        payload={"source_id": "{deposit_id}", "entity_type": "FIXED_DEPOSIT",
                 "type": "INTEREST_ACCRUAL", "amount": "12.50", "description": "monthly accrual"},
        expected_status=200,
    ),
]
